config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :hostels, only: [:index, :show] do
    resources :bookings do
       resources :payments, only: [:new, :create]
      end
  end
  resources :services, only: [:index, :show]

  resources :users, only: [:show, :edit]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
        <a href="#">About</a>
        <span> | </span>
        <a href="#">Team</a>
      </div>
       <div class="footer-copyright">
         <a href="#">Gimme Shelter, Inc.</a>
      </div>
</div>

app/views/shared/_navbar.html.erb
<div class="<%= params[:controller] == 'pages' ? 'navbar-home' : 'navbar-wagon' %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "profile_picture.jpg", class: "avatar dropdown-toggle image-cropper", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                  <i class="far fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
            </li>
            </li>
                <li><a href="#"><i class="fas fa-home"></i> My bookings</a></li>
            <li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="hidden-md hidden-lg">
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown ">
          <%= image_tag "profile_picture.jpg", class: "avatar dropdown-toggle image-cropper", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
                <%= link_to user_path(current_user) do %>
                  <i class="far fa-user"></i> <%= t(".profile", default: "  Profile") %>
                <% end %>
            </li>
            <li>

              <%= link_to hostel_bookings_path(current_user) do  %>
               <i class="fas fa-bed"></i>   My bookings
               <% end %>

             </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
               <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "  Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
        <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>