config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :hostels, only: [:index, :show] do
    resources :bookings do
       resources :payments, only: [:new, :create]
      end
  end
  resources :services, only: [:index, :show]

  resources :users, only: [:show, :edit]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/pages/home.html.erb
<!-- <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="banner item active">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1527355360335-e80ea36fe2a1?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=138160e46940ccb5b5d30ff59ea9dfc1&auto=format&fit=crop&w=800&q=60" >
    </div>
    <div class="banner item">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1527223090385-ca195a6c3acc?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7cd6f74a9213ce6748c78118782a8a82&auto=format&fit=crop&w=800&q=60">
    </div>
    <div class="banner item">
      <img class="d-block w-100" src="https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=04c27a9ea6ed87838d712ae831afa974&auto=format&fit=crop&w=800&q=60">
    </div>
  </div>
</div>

<script>$('.carousel').carousel()</script> -->




<div class="banner " style="background-image:  url('https://images.unsplash.com/photo-1509059852496-f3822ae057bf?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=a26fa6ef06a6598afacebe2cde9be106&auto=format&fit=crop&w=1112&q=80');">
  <div class="banner-content">
       <p>
          <strong><span id="banner-typed-text"></span></strong>
       </p>
  </div>
</div>

<%#= simple_form_for [@hostel, @booking] do |f| %>
 <%#= f.input :date, input_html: { id: 'datepicker' }  %>
<%#= javascript_pack_tag 'datepicker' %>
<!-- <p>Welcome to Gimme Shelter. We provide a quick and effective way to book a hostel bed for those most in need.</p>
<p>Give shelter to a homeless person today</p>
<div class= homepage-description>
  <p>
  <span id="banner-typed-text"></span>
</p>
</div> -->

<div class="wrapper">
  <div class="search">

   <%= form_tag hostels_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control input-curve",
              id: "hostel_address",
            placeholder:  "Current location..."%>
            <i class="fas fa-location-arrow"></i>

  </div>
  <div class="homebuttons">
    <div class="hostelbook">
      <input type="submit" value="Find a Hostel"  class= "btn btn-book btn-home" >
      <%#= link_to "Find a Hostel", hostels_path, class: "btn btn-book" %> <br>
    </div>
    <% end %>
      <%= link_to "Find a Service", services_path, class: "btn btn-service btn-home" %>
  </div>
</div>