config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :hostels, only: [:index, :show] do
    resources :bookings do
       resources :payments, only: [:new, :create]
      end
  end
  resources :services, only: [:index, :show]

  resources :users, only: [:show, :edit]

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/hostel.rb
class Hostel < ApplicationRecord
  monetize :price_cents
  has_many :users, through: :bookings
  has_many :bookings
  validates :name, presence: true
  validates :address, presence: true
  # validates :description, presence: true
  # validates :price, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search_address,
    against: [ :address ],
    using: {
      tsearch: {any_word: true}
      # tsearch: {prefix: true}
    }

   pg_search_scope :search_room_type,
    against: [ :female ],
    using: {
      tsearch: { prefix: true }
    }

  pg_search_scope :search_pets,
    against: [ :pets ],
    using: {
      tsearch: { prefix: true }
    }

   pg_search_scope :search_alcohol,
    against: [ :alcohol],
    using: {
      tsearch: { prefix: true }
    }


end

app/controllers/hostels_controller.rb
class HostelsController < ApplicationController

  def index
    # location
    if params[:query].present?
      @hostels = Hostel.search_address(params[:query]).where.not(latitude: nil, longitude: nil)
    else
      @hostels = Hostel.where.not(latitude: nil, longitude: nil)
    end

    # female_only
    if params[:female_only].present?
      @hostels = @hostels.where(female_only: params[:female_only])
    end

    # pets
    if params[:pets].present?
      @hostels = @hostels.where(pets: params[:pets])
    end

    # alcohol
    if params[:alcohol].present?
      @hostels = @hostels.where(alcohol: params[:alcohol])
    end

    # if params[:query].present?
    #    @hostels = Hostel.search_room_type(params[:query]).where.not(female: false)
    # else
    #   @hostels = Hostel.where.not(female: false)

    # end

    @icon_url = ActionController::Base.helpers.image_url('orangepin.png')
    @user_icon = ActionController::Base.helpers.image_url('user-icon.png')

     @markers = @hostels.map do |hostel|
      {
        lat: hostel.latitude,
        lng: hostel.longitude,
        icon: { url: @icon_url}

       }
    end

    if headers['Content-Type'] == 'application/javascript'
      render partial: 'hostels/index'
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    # @booking = Booking.create(user_id: current_user)
    @hostel = Hostel.find(params[:id])
    @booking = Booking.create(hostel_sku: @hostel.sku, amount: @hostel.price, state: 'pending', user: current_user, hostel: @hostel)
  end
end

app/views/hostels/index.html.erb
<div class="filter-container">
  <form action="/hostels" method="get">
    <label class="dropdown-filter">
      <div class="btn-filter">
        Room
      </div>
      <input type="checkbox" class="dd-input" id="test">
      <div class="dd-menu">
        <label for="female-only-false">
          <input type="checkbox" class="hidden" value="false" id="female-only-false" name="female_only">
          Mixed Room
        </label>
        <label for="female-only-true">
          <input type="checkbox" class="hidden" value="true" id="female-only-true" name="female_only">
          Female Only
        </label>
      </div>
    </label>

    <label class="dropdown-filter">
      <div class="btn-filter">
        Pets
      </div>
      <input type="checkbox" class="dd-input" id="test">
      <div class="dd-menu">
        <label for="pets-false">
          <input type="checkbox" class="hidden" value="false" id="pets-false" name="pets">
          No Pets
        </label>
        <label for="pets-true">
          <input type="checkbox" class="hidden" value="true" id="pets-true" name="pets">
          Allows Pets
        </label>
      </div>
    </label>

    <label class="dropdown-filter">
      <div class="btn-filter">
        Alcohol
      </div>
      <input type="checkbox" class="dd-input" id="test">
      <div class="dd-menu">
        <label for="alcohol-false">
          <input type="checkbox" class="hidden" value="false" id="alcohol-false" name="alcohol">
          No Alcohol
        </label>
        <label for="alcohol-true">
          <input type="checkbox" class="hidden" value="true" id="alcohol-true" name="alcohol">
          Allows Alcohol
        </label>
      </div>
    </label>
    </label>
    <input type="submit" value="Apply" class="btn btn-apply">
  </form>
</div>

<div
  id="map"
  style="width: 100%;
  height: 255px;"
  data-markers="<%= @markers.to_json %>"
></div>

<div id='map-urls' data-marker-icon-url='<%= @icon_url %>' data-user-icon-url='<%= @user_icon %>'></div>
<div class="container">
  <div class="row">
    <div class="carousel">
      <%@hostels.each do |hostel|%>
        <div class="col-xs-12">
        <!-- insert <div class="card"> -->
          <div class="card hostel-card" style ="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path hostel.photo %>);">
            <h2 class="card-name"> <%= hostel.name %></h2>
            <h3 class="card-address"> <%= hostel.address %> </h>
          </div>
          <p class="price"><%= humanized_money_with_symbol(hostel.price)  %></p>
          <div class="btn-index">
            <%= link_to "Choose Hostel", hostel_path(hostel), class: "btn btn-book" %>
          </div>
         </div>
      <% end %>
    </div>

  </div>
</div>

<%# javascript_pack_tag "carousel" %>
<%= javascript_pack_tag 'filters' %>

app/views/hostels/show.html.erb
<div class="hostel-show">
  <%= image_tag @hostel.photo, class: "hostel-img" %>
  <h3><%= @booking.hostel_sku %> <%= @hostel.name %></h3>
  <%= form_tag hostel_booking_payments_path(@hostel, @booking) do %>
  <p class="address"><%= @hostel.address %></p>
  <div class="containter-icons">
    <% if @hostel.pets == false %>
      <% display %>
      <div class="no-dog">
        <%= image_tag "no.png", class: "no-icon" %>
        <%= image_tag "dog.png", class: "img-icon" %>
      </div>
    <% else %>
      <% display %>
      <div class="dog">
        <%= image_tag "dog.png", class: "img-icon" %>
      </div>
    <% end %>

    <% if @hostel.female_only == true %>
      <% display %>
        <%= image_tag "female.png", class: "img-icon" %>
    <% else %>
      <% display %>
        <%= image_tag "mixedroom.png", class: "img-icon" %>
    <% end %>

    <% if @hostel.alcohol == false %>
      <% display %>
        <div class="no-beer">
          <%= image_tag "no.png", class: "no-icon" %>
          <%= image_tag "beer.png", class: "img-icon" %>
        </div>
    <% else %>
      <% display %>
        <%= image_tag "beer.png", class: "img-icon" %>
    <% end %>
  </div>
<!--   <p>phone number</p> -->
    <article>
      <label class="amount">
        <span class="price-show"> <%= humanized_money_with_symbol(@booking.amount) %></span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name="Your booking for..."
      data-email="<%= current_user.email %>"
      data-description="<%= @hostel.name %>"
      data-amount="<%= @booking.amount_cents %>"
      data-currency="<%= @booking.amount.currency %>"></script>

  <% end %>


</div>















<!--     <div class="no-dog"> -->
      <%#= image_tag "no.png", class: "no-icon" %>
      <%#= image_tag "dog.png", class: "img-icon" %>
<!--     </div> -->
    <%#= image_tag "mixedroom.png", class: "img-icon" %>
<!--     <div class="no-beer"> -->
    <%#= image_tag "no.png", class: "no-icon" %>
    <%#= image_tag "beer.png", class: "img-icon" %>
<!--     </div> -->